### ISSUE TITLE
Feature Request: ntlm

### ISSUE THREAD

**Issue by sa1xx** [HaveIBeenPwned/PwnedPasswordsDownloader#10]
Would be great if we could download ntlm hashes. 
In you blog you hinted at a comming update, anything new here?

**Comment by troyhunt** [comment]
Not yet, still on the backburner.

**Comment by k4nfr3** [comment]
Hello, any news on this topic ? 🤞

**Comment by miztroh** [comment]
Related: https://github.com/HaveIBeenPwned/PwnedPasswordsAzureFunction/issues/86

**Comment by BZanten** [comment]
+1 vote here for this feature request.  We're really eagerly waiting for the NTLM hashes as well, since the Lithnet Password Protection tool is using the NTLM versions, which are not updated for > 1 year.

**Comment by stebet** [comment]
Done and delivered! https://www.troyhunt.com/pwned-passwords-adds-ntlm-support-to-the-firehose/
