### ISSUE TITLE
Will not install

### ISSUE THREAD

**Issue by JVorbeck** [HaveIBeenPwned/PwnedPasswordsDownloader#12]
I cannot get the app to install on my system. I run the command and it returns the following error:

C:\WINDOWS\system32>dotnet tool install --global haveibeenpwned-downloader
C:\Users\someuser\AppData\Local\Temp\jpq2nno2.b2t\restore.csproj : error NU1100: Unable to resolve 'haveibeenpwned-down
loader (>= 0.0.0)' for 'net6.0'.
C:\Users\someuser\AppData\Local\Temp\jpq2nno2.b2t\restore.csproj : error NU1100: Unable to resolve 'haveibeenpwned-down
loader (>= 0.0.0)' for 'net6.0/any'.
The tool package could not be restored.
Tool 'haveibeenpwned-downloader' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

Any idea what the issue with the install command is?

**Comment by JVorbeck** [comment]
This command was required to be run prior to running the install command

dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org

Then the install will run correctly. Could be helpful for others in the readme file.
Thanks!

**Comment by stebet** [comment]
Normally, adding the standard NuGet source should not be required. Do you have an idea what's causing dotnet to not know about it? @JVorbeck @Barbarrosa

**Comment by Barbarrosa** [comment]
@stebet Not sure about the case I found, but I looked it up & found people talking about several causes e.g. certain VSCode updates or package manager installation scripts.
