### ISSUE TITLE
Downloaded text file has some lines that are shorter than 40 characters

### ISSUE THREAD

**Issue by Stray216** [HaveIBeenPwned/PwnedPasswordsDownloader#20]
The download, after 3 to 4 failed attempts, will report 100% complete.
The text file however has some lines where the hashes are not exactly 40 characters, but exactly 32 characters long.

[These lines in particular](https://pastebin.com/N2SzUijC)

I've made [an issue](https://github.com/mihaifm/HIBPOfflineCheck/issues/60) on a plugin for KeePass (HIBPOfflineCheck) and apparently the hashes are always supposed to be 40 characters long.

So (1) why does the download fail so often and (2) why do some lines not have 40 characters?

**Comment by Stray216** [comment]
So by now I have tried these commands in order to download the text file.
All of them fail at 3-4 times before going through 100%.

`haveibeenpwned-downloader.exe pwnedpasswords`
`haveibeenpwned-downloader.exe pwnedpasswords -o -p 64`
`haveibeenpwned-downloader.exe pwnedpasswords -o -p 1`

Everytime there are some lines in the text file where the hash is 32 instead of 40 characters long.

For example in pwned_passwords.txt, line 37479180 is this:

> 0B4351948312DFEB90E9505A7D392784AF1680FC:1

And in pwnedpasswords.txt, line 37479180 is this:

> 0B434FF2A4E57A8D1C762A899AAE5E0F:3

Why are they different?
Which one of them is correct?

**Comment by troyhunt** [comment]
That sounds like some NTLM hashes being mixed in with the SHA-1 versions. I've chatted with @stebet on this, we're looking into it.

**Comment by stebet** [comment]
@Stray216 What version of the downloader do you have? What is the output from `dotnet tool list -g

**Comment by stebet** [comment]
@Stray216 We have purged the Cloudflare cache and are hoping that has resolves the issue. Can you do another test and confirm?

**Comment by Stray216** [comment]
@stebet Version 0.2.8
```
C:\Users\Stray\Downloads>dotnet tool list -g
Package Id                     Version      Commands
---------------------------------------------------------------------
haveibeenpwned-downloader      0.2.8        haveibeenpwned-downloader

C:\Users\Stray\Downloads>
```

**Comment by Stray216** [comment]
> @Stray216 We have purged the Cloudflare cache and are hoping that has resolves the issue. Can you do another test and confirm?

I tried downloading the whole evening. The download never reached 100%: https://pastebin.com/zFyh3pRS
I will do more download attempts tomorrow evening.

**Comment by Stray216** [comment]
The download finally finished! Here is the full log of this evenings download attempts: https://pastebin.com/1Tqkhprc
The very last of which completed with 100%. 

After that I tested the file using a python program that prints any lines shorter than 40 characters. 
The program didn't print a single line, which means success! No line is shorter than 40 characters!

Here's the command line from the last download and the python test: https://pastebin.com/buYFY1jc

Thank you so much for your help! 😄
