### ISSUE TITLE
data breach details are send to client

### ISSUE THREAD

**Issue by tigercoding56** [HaveIBeenPwned/PwnedPasswordsDownloader#22]
i was fiddling around being a script kiddie ,
and have discovered that when using the inspect tool on firefox andd klicking the haveibeenpwned email button 
it sends a list of data breaches (or more specifically websites that suffered them )

you may want to remove that functionality as it allows script kiddies like me to find out user details quite easily (look for smaller data breaches user was involved in )

sorry but i do not know where to report bugs

**Comment by troyhunt** [comment]
There's literally a spec for listing security contacts, try this if there's something you'd like to report (please also provide more details, I'm not clear what the issue is here based on what you've said): https://haveibeenpwned.com/.well-known/security.txt

**Comment by tigercoding56** [comment]
> There's literally a spec for listing security contacts, try this if there's something you'd like to report (please also provide more details, I'm not clear what the issue is here based on what you've said): https://haveibeenpwned.com/.well-known/security.txt

ok
