### ISSUE TITLE
Question about password hashes

### ISSUE THREAD

**Issue by ethindp** [HaveIBeenPwned/PwnedPasswordsDownloader#35]
So I'm unsure where to post this, so this seems like as good of a place as any. I understand that a large amount of passwords are hashed in SHA-1, but you also have NTLM hashes. However, you don't explicitly specify whether these are hashed via LMHash or MD4 (NTHash). I ask because I'd like to use the full compliment of passwords, but to do that I obviously need to know all the hashing algorithms to use. Sorry if this isn't the right forum to use.

**Comment by troyhunt** [comment]
It should be LM. Try this:

1. Check "P@ssw0rd" here and see 83,846 results: https://haveibeenpwned.com/Passwords
2. Convert "P@ssw0rd" to an MD4 hash and get "E19CCF75EE54E06B06A5907AF13CEF42" here: https://suip.biz/?act=ntlm-hash-generator
3. Query the API for that hash prefix here: https://api.pwnedpasswords.com/range/E19CC?mode=ntlm
4. See the hash suffix with 83,846 results

**Comment by ethindp** [comment]
@troyhunt Thanks! What's the `:x` stuff at the end of hashes? Like `:4`?

**Comment by troyhunt** [comment]
Refer to the documentation here: https://haveibeenpwned.com/API/v3#SearchingPwnedPasswordsByRange
