### ISSUE TITLE
Download ordered hash-lists

### ISSUE THREAD

**Issue by w0tty55** [HaveIBeenPwned/PwnedPasswordsDownloader#36]
With the direct downloads, or the download via torrent, it was possible to choose between ordered by prevalence and ordered by hash. I cannot specify the sorting via the download tool. Could this be implemented?

**Comment by hasbachr** [comment]
in this same range of this request I would love to see an option to download the top x of hashes rather then the whole list.

**Comment by troyhunt** [comment]
Every hash prefix is stored in its own file named after that prefix and containing each corresponding suffix and a count. This is why hashes are easily downloadable via prefix but not via count.

Sorting them post-download is something I’m happy for anyone why wants to write the code to submit a PR for 🙂

Filtering is the same situation insofar as it would need to be done on the client after download. Or just use the API and all the problems raised in this issue go away!
