### ISSUE TITLE
What if you do not have NET at all

### ISSUE THREAD

**Issue by jmcunx** [HaveIBeenPwned/PwnedPasswordsDownloader#37]
is there a way to down load this data when none of my systems have NET6 or any verion of NET ?

Thanks

**Comment by gorfou** [comment]
Or, maybe this sounds completely out of this world, but I use Linux exclusively for the last 20 years.  I know there's some support with Mono, but a little platform agnosticism would have been appreciated here.

**Comment by NocFlame** [comment]
The "new" .Net plattform is Cross-platform, Open source and Free. No need for mono. Please have a look at https://dotnet.microsoft.com/en-us/download/

**Comment by nelsonjchen** [comment]
From a minor conversation on HN, @jmcunx is trying to run this on OpenBSD.

**Comment by nelsonjchen** [comment]
I think for some of us, we'll like to not have to install a pile of dependencies. For that, I think the shell script presented here:

https://github.com/HaveIBeenPwned/PwnedPasswordsDownloader/issues/30 

should suffice.

**Comment by jmcunx** [comment]
Actually I already have pwned-passwords-sha1-ordered-by-hash-v8.7z, I pulled that before the download change a while ago.

I was hoping to find is a diff between that file and what is mentioned in this post:

https://www.troyhunt.com/seized-genesis-market-data-is-now-searchable-in-have-i-been-pwned-courtesy-of-the-fbi-and-operation-cookie-monster/

**Comment by TheSemicolons** [comment]
@jmcunx Mono may be an option: https://www.mono-project.com/
![2023-04-07-181936_579x364_scrot](https://user-images.githubusercontent.com/20374463/230695157-244b1996-c29a-4f4e-85ba-4d13dca5983f.png)

**Comment by thibmo** [comment]
> Or, maybe this sounds completely out of this world, but I use Linux exclusively for the last 20 years. I know there's some support for it with with Mono, but a little platform agnosticism would have been appreciated here.

It is very platform agnostic, using .net6 which works on the main operating systems used by most people and administrators.
If you need it on bsd this badly, just spin up a small VM with Linux and write a small interface between them.

Or good luck figuring out how to work with CloudFlare from the small amount of languages that do work on Open sad. Could try NodeJS.

A rewrite using puppeteer should be easy enough if your daily driver is an Open sad system ;)

**Comment by troyhunt** [comment]
Further, the API is completely platform agnostic. If you want to download all the data without using the official downloader, here's how to do it:

for 00000 to FFFFF download hash range file

You're welcome 🙂

**Comment by jmcunx** [comment]
Hi

This can be closed,  I ended up using a Linux system to get the list.

After looking at the new file, I realized the diff would be as large as the main file :)

Anyways, thank for all the work done to maintain this list.

**Comment by jmcunx** [comment]
Hi

I just closed this issue.

After looking at the new file, I realized the diff would be as large as the main file :)

Anyways, thank for all the work done to maintain this list.

**Comment by muzso** [comment]
For people looking for a simple (just curl !) solution for HIBP password hash downloads: https://github.com/HaveIBeenPwned/PwnedPasswordsDownloader/issues/79
