### ISSUE TITLE
Document the expected sizes of common downloads.

### ISSUE THREAD

**Issue by nelsonjchen** [HaveIBeenPwned/PwnedPasswordsDownloader#39]
I'll be honest, I haven't run this yet, but how large would the downloads be?

**Comment by nelsonjchen** [comment]
https://github.com/HaveIBeenPwned/PwnedPasswordsDownloader/issues/30#:~:text=Expect%205GB%20temporary%20file%2Dusage%20and%202.5GB%20size%20of%20the%20final%20file. 

Ah, about 2.5GB final.

**Comment by troyhunt** [comment]
Definitely way more than that, the compressed versions in the old monolithic downloads were about 17GB. I think from memory it’s about 60GB total, but you’ll pull them down over HTTP compression with the downloader.

**Comment by Sukumar84** [comment]
I am not able to open the file in notepad/notepad++ due to the size of file
Any application that you use to open this text file.

**Comment by troyhunt** [comment]
I use EmEditor, no problem at all.

**Comment by AGSPhoenix** [comment]
IMO, this issue is not completed. This information is relevant to any potential user of the software and should be in the README.
