### ISSUE TITLE
using a proxy for download

### ISSUE THREAD

**Issue by meikestone** [HaveIBeenPwned/PwnedPasswordsDownloader#40]
Hello,

is it possible to use a proxy to download, if yes, how can it be done?

Thanks Meike

**Comment by troyhunt** [comment]
Sure, that’s normally something you’d configure within your own network environment though.

**Comment by meikestone** [comment]
Sorry for replying lately. Yes, we have a Proxy in our network, but how do I tell this the downloader tool to use *this* proxy? Are ther any configration options - have nothing found in the documentation.

Thanks Meike
