### ISSUE TITLE
Certificate issue probably from Proxy

### ISSUE THREAD

**Issue by BlackJebus** [HaveIBeenPwned/PwnedPasswordsDownloader#44]
Hi Team and sorry for a really dumb question,

I'm sure this is My problem, not a script problem but I thought I would ask non the less.

a Linux machine

We have a proxy in place that performs ssl inspection with its own certificate/root I have installed the certificates in the Linux machine.

I can browse the web normally and use curl -l -v [google.com](http://google.com/) and do not get certificate issue.

 

I get an error when I try to run the downloader.

 

HttpRequestException: The SSL connection could not be established, see inner exception.

     AuthenticationException: The remote certificate is invalid because of errors in the certificate   

     chain: UntrustedRoot

 

 

 

I assume that I need to install the certificate somewhere for dotnet I just do not know where.

**Comment by troyhunt** [comment]
There is absolutely nothing wrong the Pwned Passwords certificate, this is an issue on your end.
