### ISSUE TITLE
Password encoding prior to hashing

### ISSUE THREAD

**Issue by mikernet** [HaveIBeenPwned/PwnedPasswordsDownloader#51]
How should the passwords be encoded into bytes prior to SHA1 hashing in order to match the database hashes?

I read that you use the `HASHBYTES` function, but I'm fairly certain that means the resulting hash will depend on how the string you are hashing is encoded into bytes given the collation of the input value. For example, an `nvarchar` input value to the function that uses a UTF8 collation will result in a different hash vs an `nvarchar` input value using a non-UTF8 collation (which defaults to UTF-16 / UCS-2) v.s. a `varchar` input value, for any password containing non-ASCII characters.

For portability and broad support I would think UTF8 should be used, but not sure what you actually used, and I don't see it specified anywhere.

**Comment by mikernet** [comment]
More specifically, what should be used from C# to generate the correct hash value:

```cs
static string GetSHA1Hash(string input)
{
    using SHA1 sha1 = SHA1.Create();
    // What encoding should be used here to produce the correct hash?
    byte[] inputBytes = Encoding.UTF8.GetBytes(input); 
    byte[] hashBytes = sha1.ComputeHash(inputBytes);

    return Convert.ToHexString(hashBytes);
}
```

**Comment by troyhunt** [comment]
Hi @mikernet, the API docs say UTF-8: https://haveibeenpwned.com/API/v3#PwnedPasswords

**Comment by mikernet** [comment]
Perfect, thank you!
