### ISSUE TITLE
Is it now compatible with NET8 ?

### ISSUE THREAD

**Issue by christianGRogers** [HaveIBeenPwned/PwnedPasswordsDownloader#56]

**Comment by mokkymiah** [comment]
Any update on this?

**Comment by Noobgamer0111** [comment]
FYI: @christianGRogers @mokkymiah 

Yes, I installed the PPDL by first installing dotnet v8 (v8.0.300) via winget in an admin PowerShell window.
Note: Admin perms are required if you want .NET SDK to be accessible to all users on your machine.

After that I ran, "dotnet tool install --global haveibeenpwned-downloader".

Proof:
![image](https://github.com/HaveIBeenPwned/PwnedPasswordsDownloader/assets/60173797/91c5d870-9c42-4943-b85e-94a00647072c)

**Comment by christianGRogers** [comment]
real shit
