### ISSUE TITLE
How frequently the data is getting updated on HIBP

### ISSUE THREAD

**Issue by Ranjeet116966** [HaveIBeenPwned/PwnedPasswordsDownloader#63]
Apologies for posting this here, I know this is not the right place to ask this but i couldn't find any genuine answer on the internet so posting this here, Right now i am trying Integrate the HIBP password service in my organisation and we are going to download all the sha1 hashed password from here and host them on our own database server and then query it in our system only. For that i wanted to know how frequently the data got updated in HIBP and new passwords are added to the HIBP database, Let's say if they add new list of passwords in their database after i integrate the current list of password in my system so will those new passwords be available to query from this PwnedPasswordsDownloader so that i can update my database as well.

**Comment by troyhunt** [comment]
There's no strict cadence for releases, it's very much up to law enforcement in terms of how much they want to feed in and if we come across significant corpuses of previously unseen plain text passwords. The advice remains to prioritise using the online k-anonymity service as it makes this issue entirely redundant.
