### ISSUE TITLE
Feature request: Allow sorting of hashes by occurrence count

### ISSUE THREAD

**Issue by mbumd** [HaveIBeenPwned/PwnedPasswordsDownloader#64]
Thanks for all of your work with this tool. One of the options for downloading the list of passwords prior to this tool's introduction was a list sorted by number of occurrences. It would be nice to have the ability to download such a list via this tool.

**Comment by troyhunt** [comment]
This one is a bit of an edge case outside most practical uses of the service. If order is important, it's best you implement your own sorting on the downloaded corpus of hashes.

**Comment by CuteistFox** [comment]
> This one is a bit of an edge case outside most practical uses of the service. If order is important, it's best you implement your own sorting on the downloaded corpus of hashes.

At least have a torrent updating monthly
