### ISSUE TITLE
Hash file decoder. 

### ISSUE THREAD

**Issue by Daniel3356** [HaveIBeenPwned/PwnedPasswordsDownloader#72]
file `pwnedpasswords.txt` looks like that with SHA1: 
```
003A1277F550445A6790977FF256FFA4224B2FBC:1
003A127950A356C6B071F5C0C16E46D2AD74753D:2
003A1279B07BFE7CA3637834839F28F3AB81B485:3
003A1284077A891C266F7EE331EB8C69A2C19CC3:6
003A1286615976BCC0D95332BAA0A6804BC6D0B8:1
003A128D2CC0C27C068885B15478623CC7AFE2FC:2
003A128E394F052EA196908DCA9ACB11047437FF:1
003A129604FA10BE0E5771FEFE6BB23202C6BC34:4
003A129A46851B49B308CC0C3062E9EAF64C6E3A:3
003A12A197D4D0B803D7DE927EB77A191508CF37:4
003A12A2A178EAE7F1BCC23F42C7CF9C249B30A4:1
```

Now can I convert it into the raw un hashed password? Are they any docs?

**Comment by quantumpacket** [comment]
That's not how hashing works.

**Comment by AdrianLThomas** [comment]
Hashing is a one way process (password --> hash). In order to see if a password is matching the hash, you must first hash it.

**Comment by troyhunt** [comment]
> So now can I convert `003A1277F550445A6790977FF256FFA4224B2FBC` into the raw password? 

You're not meant to, that's the whole point: https://www.troyhunt.com/understanding-have-i-been-pwneds-use-of-sha-1-and-k-anonymity/

**Comment by Daniel3356** [comment]
OK thanks @troyhunt
