### ISSUE TITLE
Downloading new data between June and October same number of hashes. 

### ISSUE THREAD

**Issue by scikgribbon** [HaveIBeenPwned/PwnedPasswordsDownloader#80]
Hi potentially a bit of a silly issue I'm sure it could be explained but can't for the life of me work out why. 

I run the downloader monthly and build a db while comparing the hash count between months to know when new hashes are added to rebuild a password checker. 

Since June the hash count has remained the same maybe a simple explanation as to why. It seems odd that between now and then no further hashes were added.

**Comment by stebet** [comment]
That sounds right. The hashes aren't updated that frequently, since there aren't that many data breaches these days with clear-text passwords. We updated them on November 1st, 2024, and the last update before that was on May 29th, 2024.

**Comment by scikgribbon** [comment]
Amazing thank you @stebet is there somewhere we can view when there are updates and saves having to rebuild every month without reason?

**Comment by stebet** [comment]
> Amazing thank you @stebet is there somewhere we can view when there are updates and saves having to rebuild every month without reason?

Not now but we should make that clear somewhere @troyhunt.
